---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-nginx
spec:
  selector:
    matchLabels:
      app: dpl-nginx
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: dpl-nginx
    spec:
      containers:
      - name: master
        image: nginx:1.10
        ports:
        - containerPort: 80

---          
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: dpl-nginx        
spec:
  type: NodePort
  ports:
    - port: 80 
  selector:
    app: dpl-nginx        

